### ISSUE TITLE
Matlab module is missing

### ISSUE THREAD

**Issue by shahmustafa** [ilaydayaman/CNN_for_SLR#1]
CNN.m module described in README.md is missing in CNN_for_SLR

**Comment by ttamyurek** [comment]
I've uploaded the MATLAB codes, thank you for your notification.

**Comment by ANNM190605** [comment]
I have executed CNN code in vivado 2017.3. But I am getting error in  simulated waveform.

**Comment by gonultasbu** [comment]
@ANNM190605 can you please provide more details about the error you're getting?
