### ISSUE TITLE
some question about simulation

### ISSUE THREAD

**Issue by kangliyu1** [ilaydayaman/CNN_for_SLR#2]
Hello! I am very interested in your open source design, do you have more detailed documentation? Because there are some places I don't understand,
How to determine whether the simulation results are correct? How did your simulation data come about? Can you share the whole simulation process? Including from the acquisition of simulation data to the final simulation output results. I hope you can give some pointers, thank you very much!

**Comment by ilaydayaman** [comment]
Hi, unfortunately we do not have a more detailed documentation we can share. We compared the simulation results with the results in MATLAB and see if they are matching.

**Comment by kangliyu1** [comment]
> Hi, unfortunately we do not have a more detailed documentation we can share. We compared the simulation results with the results in MATLAB and see if they are matching.

thank you for your reply! So, is your project fully functional? Is it the one that can be used directly? Can I ask you some questions about the project in the future?

**Comment by ilaydayaman** [comment]
Hi again! The project is not completely finished, however we hope it can be a guide for anyone who would like to do similar projects. We try to answer as much as questions possible.
