### ISSUE TITLE
vivado simulation is wrong

### ISSUE THREAD

**Issue by wgq18** [ilaydayaman/CNN_for_SLR#3]
Hello, i run simulation in vivado 2018.3, but fc_output is X. How to fix this problem?
![Screenshot from 2023-09-15 10-41-04](https://github.com/ilaydayaman/CNN_for_SLR/assets/58140458/6c282347-6b4c-48ce-957b-66db956c0aa4)

**Comment by ilaydayaman** [comment]
Hi, 
Here are a few things you can check to solve the problem: 
1. Is your clock properly defined? What is your clock frequency? Do you have any timing violations?
2. How did you initialize your memories? What kind of memories did you use? Distributed or block? ROM or RAM?
3. Do you have any latches in the design?

**Comment by ilaydayaman** [comment]
Due to inactivity, I close this issue.
